import React from 'react'

export const Ipageview = () => {
  return (
    <div className="pageview-include-content">
      <div className="table-title">
        <h3>PageView</h3>
        </div>
        <div className="table-data">
        <table cellSpacing={0} cellPadding={0} className="table-data-table">
          <thead>
            <tr>
              <th>Page Url</th>
              <th>Pageview</th>
              <th>Unique Pageview</th>
              <th>Bounce Rate</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
          </tbody>
        </table>
        </div>
    </div>
  )
}
