import React, { useState, useEffect } from "react";
import axios from "axios";

export const Ipageview = () => {
  const [PageView, setPageView] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    axios.get("http://192.168.1.11:8000/api/PageView").then((result) => {
      if (result.data.status === 200) {
        // console.log(result.data.value[0]['label'])
        setLoading(false);
        setPageView(result.data.value);
      }
    });
  }, []);
  return (
    <div className="pageview-include-content">
      <div className="table-title">
        <h3>PageView</h3>
        </div>
        <div className="table-data">
        <table cellSpacing={0} cellPadding={0} className="table-data-table">
          <thead>
            <tr>
              <th>Page Url</th>
              <th>Pageview</th>
              <th>Unique Pageview</th>
              <th>Bounce Rate</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>70%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>/index</td>
              <td>400</td>
              <td>100</td>
              <td>40%</td>
            </tr>
          </tbody>
        </table>
        </div>
    </div>
  )
}
